namespace aDVanceERP.Modulos.Inventario; 

public static class ModuloInventario {
    public const string Nombre = "MOD_INVENTARIO";

    public static readonly string[] Permisos = {
        "MOD_INVENTARIO_TODOS",
        "MOD_INVENTARIO_PRODUCTOS_TODOS",
        "MOD_INVENTARIO_PRODUCTOS_ADICIONAR",
        "MOD_INVENTARIO_PRODUCTOS_EDITAR",
        "MOD_INVENTARIO_PRODUCTOS_ELIMINAR",
        "MOD_INVENTARIO_MOVIMIENTOS_TODOS",
        "MOD_INVENTARIO_MOVIMIENTOS_ADICIONAR",
        "MOD_INVENTARIO_MOVIMIENTOS_EDITAR",
        "MOD_INVENTARIO_MOVIMIENTOS_ELIMINAR",
        "MOD_INVENTARIO_ALMACENES_TODOS",
        "MOD_INVENTARIO_ALMACENES_ADICIONAR",
        "MOD_INVENTARIO_ALMACENES_EDITAR",
        "MOD_INVENTARIO_ALMACENES_ELIMINAR"
    };
}