namespace aDVanceERP.Modulos.Contactos; 

public static class ModuloContactos {
    public const string Nombre = "MOD_CONTACTO";

    public static readonly string[] Permisos = {
        "MOD_CONTACTO_TODOS",
        "MOD_CONTACTO_PROVEEDORES_TODOS",
        "MOD_CONTACTO_PROVEEDORES_ADICIONAR",
        "MOD_CONTACTO_PROVEEDORES_EDITAR",
        "MOD_CONTACTO_PROVEEDORES_ELIMINAR",
        "MOD_CONTACTO_MENSAJEROS_TODOS",
        "MOD_CONTACTO_MENSAJEROS_ADICIONAR",
        "MOD_CONTACTO_MENSAJEROS_EDITAR",
        "MOD_CONTACTO_MENSAJEROS_ELIMINAR",
        "MOD_CONTACTO_CLIENTES_TODOS",
        "MOD_CONTACTO_CLIENTES_ADICIONAR",
        "MOD_CONTACTO_CLIENTES_EDITAR",
        "MOD_CONTACTO_CLIENTES_ELIMINAR",
        "MOD_CONTACTO_CONTACTOS_TODOS",
        "MOD_CONTACTO_CONTACTOS_ADICIONAR",
        "MOD_CONTACTO_CONTACTOS_EDITAR",
        "MOD_CONTACTO_CONTACTOS_ELIMINAR"
    };
}